name: Deploy

on:
  push:
    branches: [develop, master]

jobs:
  build-react:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npm run lint --if-present
    - name: Build
      run: npm run build --if-present
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./build

  build-contracts:

    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      INFURA_ENDPOINT: ${{ secrets.INFURA_ENDPOINT }}

    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Test contracts
      run: npx hardhat test
    - name: Compile and deploy contracts to Ropsten
      run: npx hardhat run scripts/deploy.js
